### PR TITLE
Updated index.html to reflect live version

### PR DESCRIPTION
**Pull request by PureTryOut**
- Fixed typo's and misinformation.
- Changed download links for direct ones instead of redirecting to the forum

This version is already live on the server.

### CODE REVIEW

**Comment by ghost** [comment]
Well, i wrote in the other issue alrwady, this isn't the one I want to use 😛 

Anyway, thanks!

**Comment by ghost** [comment]
So, I looked at the code, a few things. 
- Aren't there install instructions? 
- well, I was told that they want to use gitlab in the future

**Comment by PureTryOut** [comment]
The install instructions for the client are on the (new) forums, and for the server are in the Github repo.

@D4edalus was talking about moving to Gitlab yes, but I'm not sure if he still wants it. For now the (still outdated) code is on Github, so the website should reflect that.

**Comment by ghost** [comment]
Well, as I said, please rebase your changes to  Schwertspize/schwertspize.github.io

**Comment by PureTryOut** [comment]
Ooh didn't realize that sorry. I'll make a pull request there.

**Comment by ghost** [comment]
LOOOL strange github

im sorry

**Comment by ghost** [comment]
easiest thing now would be to transfer ownership of my repository, for that i need admin access in this organization. im sorry for the inconvenience :/ @D4edalus

**Pull request closed without merging**
